-- MySQL Script generated by MySQL Workbench
-- 03/12/15 15:56:15
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bancoschoolsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoschoolsystem` DEFAULT CHARACTER SET utf8 ;
USE `bancoschoolsystem` ;

-- -----------------------------------------------------
-- Table `bancoschoolsystem`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoschoolsystem`.`aluno` (
  `matricula` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `data_Nasc` VARCHAR(45) NULL DEFAULT NULL,
  `idade` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `nome_Pai` VARCHAR(45) NULL DEFAULT NULL,
  `nome_Mae` VARCHAR(45) NULL DEFAULT NULL,
  `data_Mat` VARCHAR(45) NULL DEFAULT NULL,
  `capacidade` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_Turma` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancoschoolsystem`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoschoolsystem`.`professor` (
  `matricula` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `cod_Turma` VARCHAR(45) NULL DEFAULT NULL,
  `professorcol` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancoschoolsystem`.`turma1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoschoolsystem`.`turma1` (
  `Cod_turma` INT(11) NOT NULL,
  `AnoNivel` VARCHAR(45) NULL DEFAULT NULL,
  `Turma` VARCHAR(45) NULL DEFAULT NULL,
  `Turno` VARCHAR(45) NULL DEFAULT NULL,
  `Sala` VARCHAR(45) NULL DEFAULT NULL,
  `Ano` VARCHAR(45) NULL DEFAULT NULL,
  `Disciplina1` VARCHAR(45) NULL DEFAULT NULL,
  `Disciplina2` VARCHAR(45) NULL DEFAULT NULL,
  `Disciplina3` VARCHAR(45) NULL DEFAULT NULL,
  `Disciplina4` VARCHAR(45) NULL DEFAULT NULL,
  `Disciplina5` VARCHAR(45) NULL DEFAULT NULL,
  `Disciplina6` VARCHAR(45) NULL DEFAULT NULL,
  `Disciplina7` VARCHAR(45) NULL DEFAULT NULL,
  `Disciplina8` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_turma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancoschoolsystem`.`usuarioad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoschoolsystem`.`usuarioad` (
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `conf_Senha` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
